name: ci-golang-workflow
on:  
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    # Matriz de testes com versões do Go a serem testadas
    strategy:
      matrix:
        go: ['1.18', '1.19']
    steps:
    #  Cria as actions
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      # Executa as configs da Matriz
        with:
          go-version: ${{matrix.go}}
    #  Cria os comandos
      - run: go test
      - run: go run main.go